# Generated by Django 5.1.7 on 2025-12-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass'),
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
